services:
  mysql_db:
    image: mysql:8.0
    container_name: expense-tracker-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: expense_tracker
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: expense-tracker-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/expense_tracker
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      mysql_db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: expense-tracker-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

# Define volumes as a top-level key
volumes:
  mysql_data: