server:
  port: 8080

jwt:
   secret: ${JWT_SECRET:GIx5+Qc6zSJ9qpJAzUjejwiAncjQpIBWXDbAHRLI6L8=} # Secret key from environment
   expiration: ${JWT_EXPIRATION:36000000} # Default to 10 hours if not set

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/expense_tracker
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  retry:
    initial-interval: 5s
    max-attempts: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


